### ISSUE TITLE
Remove API function get_mesh_vertex_ids_from_positions and get_mesh_vertices

### ISSUE THREAD

**Issue by IshaanDesai** [precice/python-bindings#155]
Deprecate the bindings API function `get_mesh_vertex_ids_from_positions` because the original API function `getMeshVertexIDsFromPositions` is being deprecated: https://github.com/precice/precice/issues/1248.

**Comment by uekerman** [comment]
You could directly delete, not deprecate, right?

**Comment by IshaanDesai** [comment]
> You could directly delete, not deprecate, right?

The original issue in the preCICE repo said deprecate and hence I also indicated deprecation here. But yes, if we are breaking the upstream develop anyway then one can just remove the function here altogether.
