### ISSUE TITLE
Make sure that complete API is supported by bindings

### ISSUE THREAD

**Issue by BenjaminRueth** [precice/python-bindings#16]
This issue branches from https://github.com/precice/precice/issues/520

- [x] add `getVersion`
- [x] communicator argument for `Interface` constructor #19 
- [x] add `isTimeWindowComplete` see https://github.com/precice/python-bindings/issues/20
- [x] more?

**Comment by IshaanDesai** [comment]
This issue cannot be closed by only adding the `get_version_information` call to the python bindings because the implementation of `isTimeWindowComplete` is in process here: https://github.com/precice/precice/pull/619
