### ISSUE TITLE
No initialize_data() function in v2.5.0.1

### ISSUE THREAD

**Issue by j-signorelli** [precice/python-bindings#163]
The newest release (v2.5.0.1) no longer has "initialize_data()". The previous one (v2.5.0.0) does.

**Comment by IshaanDesai** [comment]
The function `initialize_data()` is there on the release branch `python-bindings-v2.5.0.1`: https://github.com/precice/python-bindings/blob/python-bindings-v2.5.0.1/cyprecice/cyprecice.pyx#L114 and hence is also part of the release. I use this function regularly while using `v2.5.0.1`. Did you get an error regarding this function?

**Comment by BenjaminRodenberg** [comment]
Did you maybe accidentally install the develop version of the bindings? On the develop branch, `initialize_data` indeed does not exist anymore. 

You can check the version of the python bindings by executing the following from your terminal:

```
python3 -c "import precice; print(precice.__version__)"
```

This should give you `v2.5.0.1` if you installed `v2.5.0.1`. If you see a commit hash, you might accidentally have installed the develop version. Please post the result here that we know what's happening on your side.

**Comment by j-signorelli** [comment]
That was it, my apologies, I didn't recognize the default branch was the develop one. Thanks for pointing that out.

**Comment by BenjaminRodenberg** [comment]
> That was it, my apologies, I didn't recognize the default branch was the develop one. Thanks for pointing that out.

No problem and thank you for replying :+1: Nice to hear that we could help you.
