### ISSUE TITLE
Segmentation fault when using pyprecice `v2.5.0.2`

### ISSUE THREAD

**Issue by IshaanDesai** [precice/python-bindings#182]
A segmentation fault [is observed](https://github.com/precice/micro-manager/actions/runs/5586913191/job/15130470393#step:6:34) when pyprecice `v2.5.0.2` is used on a fresh Ubuntu 22.04 machine. The error was also observed by a user: https://precice.discourse.group/t/some-mistake-when-i-test-it-after-finish-install-python-bindings-help-me/1499

~~Initial investigation shows that the cause might be in the function `initialize_data()`, but further investigations are necessary.~~

**Comment by mosayebshams** [comment]
We are observing the same issue. It hits the segmentation fault error whenever my Python solver calls `write_block_scalar_data` either `read_block_scalar_data` or any read/write action in general! It can be reproduced using the Python solvers of https://github.com/precice/tutorials/tree/master/elastic-tube-1d.

**Comment by IshaanDesai** [comment]
We have realized that the segmentation fault is occuring due to a breaking change in the private class name mangling in Cython v3.0.0 which was released just last week (exactly when the bindings broke). More details: https://cython.readthedocs.io/en/latest/src/userguide/migrating_to_cy30.html#class-private-name-mangling
We are preparing a compatibility release which will be out shortly.

**Comment by IshaanDesai** [comment]
Closed via 5608af12d8b97b7144d672e9f3fc33267c3cd595
