### ISSUE TITLE
Workflow releasing docker container does not build `master` branch

### ISSUE THREAD

**Issue by BenjaminRodenberg** [precice/python-bindings#195]
https://github.com/precice/python-bindings/blob/c0288c880e64a20848d2275c2b057e5041ee057e/.github/workflows/build-docker.yml#L54-L62

The code above does not provide the correct branch to the dockerfile, if running from `master`, i.e. a release. This results in an incorrect release.

If I run the following locally, everything works:

```
python-bindings/tools/releasing/packaging/docker$ docker build -t precice/python-bindings:latest --build-arg branch=v3.0.0.0 .
```

Note: `--build-arg=v3.0.0.0` is needed and not `--build-arg=master`, because `master` contains https://github.com/precice/python-bindings/commit/536d385a0fdb77656011f45cf32ab9b3be16de3b

One can check for the correct version of the bindings being packaged by
```
docker run -ti precice/python-bindings:latest
python3 -c "import precice; print(precice.__version__)"
```

At the current state this breaks our automated packaging pipeline and requires manually releasing the docker container.

**Comment by BenjaminRodenberg** [comment]
I manually released the latest version of the python bindings now to `precice/python-bindings:latest`. Before the next release we should either fix this issue or deactivate the workflow. The way how things are working currently is very misleading.

**Comment by MakisH** [comment]
Sounds like duplicate of https://github.com/precice/python-bindings/issues/191

**Comment by BenjaminRodenberg** [comment]
It's not a duplicate, but it was a false alert. The Dockerfile I used to manually do the release was outdated. With the up-to-date Dockerfile I now run into the issue described in #191, but this is a different story.
