### ISSUE TITLE
Move constants into appropriate module?

### ISSUE THREAD

**Issue by BenjaminRodenberg** [precice/python-bindings#26]
In the python API we currently call the constants directly from the module `precice` (e.g. `precice.write_iteration_checkpoint()`). This is not consistent with the C++ API, where constants live in their own namespace `precice::constants` (e.g. `precice::constants::actionWriteIterationCheckpoint()`).

**Comment by BenjaminRueth** [comment]
Note that this change will break our tests and tutorials, since we will have to update them accordingly.

**Comment by IshaanDesai** [comment]
Constants no longer exist in the development version of the preCICE API, and they will no exist for the upcoming release.
