### ISSUE TITLE
Installation Problem

### ISSUE THREAD

**Issue by DanielBorgesOliveira** [precice/python-bindings#53]
Hi,

I am getting some errors when trying to install the python-bindings.

When I ran the command `python3 setup.py build_ext` I get the following errors:

`/usr/src/precice/python-bindings/precice.cpp:3196:60: error: ‘class precice::SolverInterface’ has no member named ‘isTimeWindowComplet ’; did you mean ‘isTimestepComplete’?
   __pyx_t_1 = __Pyx_PyBool_FromLong(__pyx_v_self->thisptr->isTimeWindowComplete()); if (unlikely(!__pyx_t_1)) __PYX_ERR(0, 284, __pyx_L1_error)
                                                            ^~~~~~~~~~~~~~~~~~~~
                                                            isTimestepComplete
/usr/src/precice/python-bindings/precice.cpp: In function ‘PyObject* __pyx_pf_7precice_9Interface_30mark_action_fulfilled(__pyx_obj_7precice_Interface*, PyObject*)’:
/usr/src/precice/python-bindings/precice.cpp:3454:26: error: ‘class precice::SolverInterface’ has no member named ‘markActionFulfilled’
   __pyx_v_self->thisptr->markActionFulfilled(__pyx_t_1);
                          ^~~~~~~~~~~~~~~~~~~
error: command 'x86_64-linux-gnu-gcc' failed with exit status 1`

What can I do to solve the problem?

Thank you.

**Comment by IshaanDesai** [comment]
Hi @DanielBorgesOliveira! which branch of the bindings are you building from? Or did you download the package from the [latest release](https://github.com/precice/python-bindings/releases/tag/v2.1.0.1)?

**Comment by MakisH** [comment]
@DanielBorgesOliveira It looks like you are using an old preCICE version (1.x) with the latest bindings (for preCICE 2.1). The API method `isTimestepComplete` [was renamed](https://github.com/precice/precice/wiki/Porting-adapters-from-preCICE-1.x-to-2.x#sorted-out-duplicate-meaning-of-timestep) to `isTimeWindowComplete` in v2.0.0, as before there was a mix-up between *solver time step* and *coupling time step* and as this distinction becomes more and more important towards adding the time interpolation feature.

@IshaanDesai interestingly, however, the message reports `isTimeWindowComplet ` (looks like an `e` is missing at the end).

**Comment by IshaanDesai** [comment]
@MakisH indeed that part confuses me, where there is an `e` missing. I cannot find a `isTimeWindowComplet` in the bindings or any associated packages.
@DanielBorgesOliveira I rechecked and if you use preCICE `v2.1` and python-bindings `v2.1.0.1` the installation should go through on a Ubuntu system.

**Comment by DanielBorgesOliveira** [comment]
Hi friends,

For some reason, I checked out in the v1.6.1 branch when compiling Precice.
I recompiled Precice in the v2.1.0 branch and the error was gone.

Thank you all for the fast reply and apology for the inconvenience.

**Comment by MakisH** [comment]
Glad to hear that! Please let us know if you found some outdated link or any similar reason that you ended up with v1.6.1, so that we can fix it.

**Comment by DanielBorgesOliveira** [comment]
There is nothing wrong on your side. It is totally my fault.

I always write down the steps I take when compiling code and always do a checkout in the branch I am working to make sure the compilation process go as smooth as possible.

This saves me a lot of time when I am compiling I code that I already compiled in the past.

I simply copied these my annotations to compile Precice this time.

The fault, in this case, was that I checked out the Precice code in branch v1.6.1 and not checked out in the Bindings code.

I simply checked out in v2.1.0 in Precice code and checked out in v2.0.0.2rc2 for Python-Bindings, compiled again and the problem was solved.

Thank you much very.

**Comment by IshaanDesai** [comment]
@DanielBorgesOliveira no problem at all! If you want to be fully consistent with the latest preCICE release and the latest python-bindings release then for preCICE `v2.1.0` you can use the corresponding released version of the python-bindings which is [v2.1.0.1](https://github.com/precice/python-bindings/releases/tag/v2.1.0.1)

**Comment by DanielBorgesOliveira** [comment]
I will do it. Thank you very much.
