### ISSUE TITLE
Defining empty mesh in the interface gives an error

### ISSUE THREAD

**Issue by IshaanDesai** [precice/python-bindings#55]
For parallel simulations, not every rank will consist a part of the coupling interface and hence the ranks which have no coupling interface will define meshes in preCICE using an empty list or empty numpy array. For example if `set_mesh_vertices()` is called with an empty list or empty array in place of the intended function argument for mesh coordinates, the following error is seen:
```
File "precice.pyx", line 519, in precice.Interface.set_mesh_vertices
ValueError: need more than 1 value to unpack
```
This scenario needs to be handled properly in the bindings. If it is intended that such empty ranks do not attempt to set up a mesh in preCICE then a proper error message would help here.

**Comment by uekerman** [comment]
Better than throwing an error would actually be a "nop", so it should just run through without doing anything. That's also the behavior of C++ preCICE itself.
