### ISSUE TITLE
Provide spack package

### ISSUE THREAD

**Issue by BenjaminRodenberg** [precice/python-bindings#61]
@ajaust and I started to work on a spack package on [this fork](https://github.com/ajaust/spack).

**Comment by ajaust** [comment]
The corresponding pull request can be found here: https://github.com/spack/spack/pull/19558

**Comment by ajaust** [comment]
See https://github.com/precice/python-bindings/pull/63 for some patch needed to compile the bindings with Spack.

**Comment by ajaust** [comment]
The Spack PR has been merged. :)

**Comment by BenjaminRodenberg** [comment]
Spack package is documented (https://github.com/precice/python-bindings#using-spack). Closing this issue.
