### ISSUE TITLE
Bug: It looks like opal_init failed for some reason

### ISSUE THREAD

**Issue by BenjaminRodenberg** [precice/python-bindings#72]
Reported in https://github.com/precice/systemtests/issues/262.

The error is actually an "old friend": https://github.com/precice/precice/issues/296.

Can be fixed following https://github.com/precice/precice/issues/296#issuecomment-467802979

My first careful guess is that this problem was probably reintroduced in https://github.com/precice/python-bindings/commit/f5de714567eb0b886e4bf93d03878f63cc90ffe4#diff-929be0dcb483bab373f1c5874bd371ce15db5a655bf2cfafeecea32102bb7af4L11.

**Comment by BenjaminRueth** [comment]
Same error, different setup in https://github.com/precice/python-bindings/runs/1447732359?check_suite_focus=true. Though the build is based on https://github.com/precice/python-bindings/commit/21bc2ccb67e509b78b0ba2a8f01b366a06e3bd0a, where #73 is already merged. Surprisingly enough, I have not observed this error when developing the content for #68, i.e. #73 seems to have fixed the error for the systemtests, but introduced it for the spack test. I will reopen this issue and investigate the error.

**Comment by BenjaminRodenberg** [comment]
Working on this error on https://github.com/precice/python-bindings/tree/i_72_revisited. 

* https://github.com/precice/python-bindings/commit/45249a3dd09f8364631d383b317eba5a0f2fe78f -> spack works, but systemtests fail (https://github.com/precice/python-bindings/pull/73/files)
* 135bf0852600d3530dfc4fa0298c7a7c2eaabbbb -> spack breaks, systemtests work (https://github.com/precice/python-bindings/pull/73/files)
