### ISSUE TITLE
Usability: Calling write/read_block functions with float data

### ISSUE THREAD

**Issue by BenjaminRodenberg** [precice/python-bindings#79]
A user just ran into the following error:
```
Traceback (most recent call last):
  File "/home/benjamin/python-bindings/test/test_bindings_module.py", line 198, in test_read_write_block_scalar_data_single_float
    solver_interface.write_block_scalar_data(1, 1, write_data)
  File "cyprecice/cyprecice.pyx", line 954, in cyprecice.Interface.write_block_scalar_data
    if len(values) > 0:
TypeError: object of type 'int' has no len()
```
I was able to reproduce this behavior (will push the branch in a moment) by providing a single float as `write_data` to `write_block_scalar_data`.

### Main question

Is this wrong API usage? I think the C++ preCICE API would not even compile with this kind of input. What do we want to do in the python world? The code obviously runs, but the error message is not helpful.

### Possible Solutions

Depending on the answer to the question above:

* Do we want to raise an error, because it is wrong API usage?
* Do we want to raise a warning, if we that the user is using the API in the wrong way and pass the arguments to `write_scalar_data`?
* Do we want to call the "right" function automatically depending on user input? Maybe completely entirely drop the "block" vs. "non-block", "scalar" vs. "vector" interface and call the right function depending on user input (just `read_data` and `write_data`)? We can implement this in a non-breaking fashion. This is the most pythonic, but also most radical solution, since it really deviates from the C++ API. Maybe this is a good "experimental" feature?

**Comment by BenjaminRodenberg** [comment]
We can start working on this issue on the branch [`i_79`](https://github.com/precice/python-bindings/tree/i_79) as soon as we have concluded on the original question.

**Comment by IshaanDesai** [comment]
> Do we want to raise an error, because it is wrong API usage?

According to me this is the natural step to fix this immediately. But then there are many such possible API usages where error messages are necessary. This is on-going work here: https://github.com/precice/python-bindings/pull/9 (This PR has been pending for a long time, needs to be completed in the near future :see_no_evil: )

> Do we want to call the "right" function automatically depending on user input? Maybe completely entirely drop the "block" vs. "non-block", "scalar" vs. "vector" interface and call the right function depending on user input (just read_data and write_data)? We can implement this in a non-breaking fashion. This is the most pythonic, but also most radical solution, since it really deviates from the C++ API. Maybe this is a good "experimental" feature?

This is the best solution and easily possible with the python bindings. Upvote to do this at some point in the future :+1:

**Comment by BenjaminRodenberg** [comment]
Then I will take care of the following two points:

* add proper error messages, if block operations receive something that is not a list/array
* implement experimental "smart" `read_data` and `write_data` that redirects calls depending on user input to the right functions (block/non-block and scalar/vector).

Everything will happen on [`i_79`](https://github.com/precice/python-bindings/tree/i_79) and I will create a PR.

**Comment by MakisH** [comment]
I think that a nice error message would be enough. In C++, the compiler would complain for inconsistent types, and the user would normally get the hint. In Python, the error message is only that "this does not quack" and the user needs to get that "oh, so this is not a duck, so maybe I am using the wrong type".

**Comment by BenjaminRodenberg** [comment]
I decided to not implement the "experimental" part in #80, but only the nice "this does not quck" error. Let's see, if the experimental `read_data` and `write_data` has some more "fans" before actually implementing it.

**Comment by BenjaminRodenberg** [comment]
If I get this issue right, we can close it? Feel free to reopen, if I'm wrong.
