### ISSUE TITLE
Solver dummy partly out of date

### ISSUE THREAD

**Issue by ajaust** [precice/python-bindings#90]
The solver dummy seems to be out to date, see  https://github.com/precice/python-bindings/tree/develop/solverdummy. It tells users to install the requirements to via
```
pip3 install --user -r requirements.txt
```
which seems to fail, see https://precice.discourse.group/t/python-bindings-error-solver-dummy/502/3

The `requirements.txt` expects `pyprecice==2.0`. Isn't this too strict and should be `pyprecice>=2.0`? Do we need the further version digits, i.e., `pyprecice==2.0.0.0`?

**Comment by BenjaminRodenberg** [comment]
@ajaust If I get it right #91 will close this issue?

**Comment by ajaust** [comment]
Yes, this issued is closed by #91 which has been merged.

**Comment by ajaust** [comment]
I was too fast. It has not been merged yet. Feel free to close this issue after #91 has been merged.

**Comment by BenjaminRodenberg** [comment]
> I was too fast. It has not been merged yet. Feel free to close this issue after #91 has been merged.

You are so fast. Nobody would have seen it anyway :rocket:
