### ISSUE TITLE
Remove openssh dependency as soon as this is possible

### ISSUE THREAD

**Issue by BenjaminRodenberg** [precice/python-bindings#94]
This issue is mainly a reminder.

In #76 we added `openssh` to the spack package.

As soon as https://github.com/spack/spack/pull/22115 is merged, we will be able to remove `openssh` again.

**Comment by haampie** [comment]
For me openmpi tests without system openssh work now: https://github.com/haampie-spack/ci-example

I also updated my example to just use `spack -e ./tools/environments/ci install -v --test=root` which now works well after https://github.com/spack/spack/pull/22040 was merged.

**Comment by BenjaminRodenberg** [comment]
Thanks for the notice @haampie. I'm testing this in #95 and will merge it as soon as the test are successful.
